export const stressAchievements = [
  { id: 'stress_01',
    description: 'Atingir 1 pontos de stress',
    name: 'Bronze' },
  { id: 'stress_02',
    description: 'Atingir 5 pontos de stress',
    name: 'Prata' },
  { id: 'stress_03',
    description: 'Atingir 10 pontos de stress',
    name: 'Ouro' },
  { id: 'stress_04',
    description: 'Atingir 15+ pontos de stress',
    name: 'Diamante' },
  { id: 'stress_05',
    description: 'Rolar 3 vezes seguidas um valor de stress entre 1 e 6',
    name: 'Nervos de aço' },
  { id: 'stress_06',
    description: 'Rolar 7 no teste de pânico',
    name: '' },
  { id: 'stress_07',
    description: 'Rolar 8 no teste de pânico',
    name: 'Parkinson?' },
  { id: 'stress_08',
    description: 'Rolar 9 no teste de pânico',
    name: '' },
  { id: 'stress_09',
    description: 'Rolar 10 no teste de pânico',
    name: '' },
  { id: 'stress_10',
    description: 'Rolar 11 no teste de pânico',
    name: '' },
  { id: 'stress_11',
    description: 'Rolar 12 no teste de pânico',
    name: '' },
  { id: 'stress_12',
    description: 'Rolar 13 no teste de pânico',
    name: '' },
  { id: 'stress_13',
    description: 'Rolar 14 no teste de pânico',
    name: '' },
  { id: 'stress_14',
    description: 'Rolar 15+ no teste de pânico',
    name: '' },
  { id: 'stress_15',
    description: 'Adquirir algum Trauma mental permanente',
    name: 'Ala psiquiátrica' },
];

export const eliminationsAchievements = [
  { id: 'eliminations_01',
    description: 'Elimine 1 humano',
    name: 'Bronze' },
  { id: 'eliminations_02',
    description: 'Elimine 10 humanos',
    name: 'Prata' },
  { id: 'eliminations_03',
    description: 'Elimine 100 humanos',
    name: 'Ouro' },
  { id: 'eliminations_04',
    description: 'Elimine 1000 humanos',
    name: 'Diamante' },
];

export const eliminationsXenomorphAchievements = [
  { id: 'eliminations_xenomorph_01',
    description: 'Elimine 1 Xenomorfo',
    name: 'Bronze' },
  { id: 'eliminations_xenomorph_02',
    description: 'Elimine 5 Xenomorfos',
    name: 'Prata' },
  { id: 'eliminations_xenomorph_03',
    description: 'Elimine 10 Xenomorfos',
    name: 'Ouro' },
  { id: 'eliminations_xenomorph_04',
    description: 'Elimine 50 Xenomorfos',
    name: 'Diamante' },
];

export const eliminationsNeomorphAchievements = [
  { id: 'eliminations_neomorph_01',
    description: 'Elimine 1 Neomorfo',
    name: 'Bronze' },
  { id: 'eliminations_neomorph_02',
    description: 'Elimine 5 Neomorfos',
    name: 'Prata' },
  { id: 'eliminations_neomorph_03',
    description: 'Elimine 10 Neomorfos',
    name: 'Ouro' },
  { id: 'eliminations_neomorph_04',
    description: 'Elimine 20 Neomorfos',
    name: 'Diamante' },
];

export const eliminationsLocalFaunaAchievements = [
  { id: 'eliminations_local_fauna_01',
    description: 'Elimine 1 animal',
    name: 'Bronze' },
  { id: 'eliminations_local_fauna_02',
    description: 'Elimine 10 animais',
    name: 'Prata' },
  { id: 'eliminations_local_fauna_03',
    description: 'Elimine 100 animais',
    name: 'Ouro' },
  { id: 'eliminations_local_fauna_04',
    description: 'Elimine 1000 animais',
    name: 'Diamante' },
];

export const eliminationsMechanicalAchievements = [
  { id: 'eliminations_mechanical_01',
    description: 'Elimine 1 sintético',
    name: 'Bronze' },
  { id: 'eliminations_mechanical_02',
    description: 'Elimine 5 sintéticos',
    name: 'Prata' },
  { id: 'eliminations_mechanical_03',
    description: 'Elimine 10 sintéticos',
    name: 'Ouro' },
  { id: 'eliminations_mechanical_04',
    description: 'Elimine 50 sintéticos',
    name: 'Diamante' },
];

export const eliminationsInnocentsAchievements = [
  { id: 'eliminations_innocents_01',
    description: 'Elimine 1 inocente',
    name: 'Bronze' },
  { id: 'eliminations_innocents_02',
    description: 'Elimine 10 inocentes',
    name: 'Prata' },
  { id: 'eliminations_innocents_03',
    description: 'Elimine 100 inocentes',
    name: 'Ouro' },
  { id: 'eliminations_innocents_04',
    description: 'Elimine 1000 inocentes',
    name: 'Diamante' },
];

export const explorationAchievements = [
  { id: 'exploration_01',
    description: 'Viajar 1 parsec',
    name: 'Bronze' },
  { id: 'exploration_02',
    description: 'Viajar 10 parsecs',
    name: 'Prata' },
  { id: 'exploration_03',
    description: 'Viajar 100 parsecs',
    name: 'Ouro' },
  { id: 'exploration_04',
    description: 'Viajar 1000 parsecs',
    name: 'Diamante' },
];

export const explorationStarSystemsAchievements = [
  { id: 'exploration_star_systems_01',
    description: 'Viajar 1 sistema estelar',
    name: 'Bronze' },
  { id: 'exploration_star_systems_02',
    description: 'Viajar 10 sistemas estelares',
    name: 'Prata' },
  { id: 'exploration_star_systems_03',
    description: 'Viajar 50 sistemas estelares',
    name: 'Ouro' },
  { id: 'exploration_star_systems_04',
    description: 'Viajar 150 sistemas estelares',
    name: 'Diamante' },
  { id: 'exploration_star_systems_05',
    description: 'Visitar um de cada tipo de sistema estelar',
    name: '' },
];

export const explorationPlanetsAchievements = [
  { id: 'exploration_planets_01',
    description: 'Pousar em 1 planeta',
    name: 'Bronze' },
  { id: 'exploration_planets_02',
    description: 'Pousar em 5 planetas',
    name: 'Prata' },
  { id: 'exploration_planets_03',
    description: 'Pousar em 10 planetas',
    name: 'Ouro' },
  { id: 'exploration_planets_04',
    description: 'Pousar em 50 planetas',
    name: 'Diamante' },
  { id: 'exploration_planets_05',
    description: 'Pousar em um de cada tipo de planeta',
    name: '' },
];

export const specialExplorationAchievements = [
  { id: 'special_exploration_01',
    description: 'Encontrar com os Engenheiros',
    name: '' },
  { id: 'special_exploration_02',
    description: 'Visitar todos os planetas dos filmes',
    name: '' },
];

export const specialEliminationsAchievements = [
  { id: 'special_eliminations_01',
    description: 'Elimine uma Rainha Alien',
    name: '' },
  { id: 'special_eliminations_02',
    description: 'Eliminar um Engenheiro',
    name: '' },
  { id: 'special_eliminations_03',
    description: 'Eliminar um de cada tipo de Xenomorfo',
    name: '' },
  { id: 'special_eliminations_04',
    description: 'Eliminar um de cada tipo de Neomorfo',
    name: '' },
];

export const xenomorphAttacksAchievements = [
  { id: 'xenomorph_attacks_01',
    description: "Receber um ataque 'Bocada na cabeça'",
    name: 'Beijo Apaixonado' },
  { id: 'xenomorph_attacks_02',
    description: "Receber um ataque 'Olhar hipnotizante'",
    name: 'Conexão de Almas' },
  { id: 'xenomorph_attacks_03',
    description: "Receber um ataque 'Brincando com a presa'",
    name: '' },
  { id: 'xenomorph_attacks_04',
    description: "Receber um ataque 'Agarrão mortal'",
    name: '' },
  { id: 'xenomorph_attacks_05',
    description: "Receber um ataque 'Cauda trituradora'",
    name: '' },
  { id: 'xenomorph_attacks_06',
    description: "Receber um ataque 'Sangue ácido'",
    name: '' },
];

export const specialAchievements = [
  { id: 'special_01',
    description: 'Completar a campanha',
    name: '' },
  { id: 'special_02',
    description: 'Ser promovido',
    name: '' },
  { id: 'special_03',
    description: 'Ser rebaixado',
    name: '' },
  { id: 'special_04',
    description: 'Pegar 3 doenças contagiosas',
    name: '' },
  { id: 'special_05',
    description: 'Ganhar um prêmio da companhia',
    name: '' },
  { id: 'special_06',
    description: 'Ir para a prisão',
    name: '' },
  { id: 'special_07',
    description: 'Pegar um animal de estimação exótico',
    name: '' },
  { id: 'special_08',
    description: 'Ser aclamado por uma multidão',
    name: '' },
  { id: 'special_09',
    description: 'Começar um motim',
    name: '' },
  { id: 'special_10',
    description: 'Evitar um motim',
    name: '' },
];
